### ISSUE TITLE
clang-format adds spacing around the : in a port declaration and the on tile[N] declaration

### ISSUE THREAD

**Issue by cdoak** [xmos/devops_clang#2]
When using this version of clang-format for XC files, it adds white space around the : of a port declaration and on tile[N] declaration.

For example:

on tile[0]: becomes on tile[0] : and
out buffered port:32 becomes out buffered port : 32

The XC compiler then complains at these statements.  It doesn't like the white space being there.

The only workaround is to turn clang format off and then back on again around these statements.  Can clang-format be updated to not add this whitespace in these statements?

**Comment by jh14778** [comment]
Hi Colin,

Yes I've observed this behaviour. This is due to the limited places where a colon can appear.
In this situation clang-format is assuming this is an inheritance colon. setting `SpaceBeforeInheritanceColon` to `false` corrects this behaviour.

I'll work on a fix so that clang-format acts intelligently around this.

However, it seems strange that the XC compiler is sensitive to whitespace there.
